added gitkeep
ictsc/ictsc-outlands pull request #5
Opened 2023-07-14 09:42 UTC by K-shir0

2023-07-14 10:12 UTC, logica0419 commented
(あまり関係ないことだけど、サービスのフォルダ名、パスカルケースじゃなくてキャメルケースで統一できるとありがたいです)

2023-07-14 10:16 UTC, K-shir0 commented
@logica0419 `Octavia` -> `octavia` って感じですか？

2023-07-14 10:17 UTC, logica0419 commented
そうです！
(あと、一応言っておくと`octavio`です)

2023-07-14 15:57 UTC, K-shir0 commented
@logica0419 レビューでスペルチェック周りの設定やディレクトリ構成などを見れていたけると助かります！！

2023-07-14 16:35 UTC, logica0419 requested changes
ありがとうございます！スペルの修正大変助かります…
一応ignoreしなくて大丈夫かなと思ったパスの一覧書いときます
actionsにはかかわらないですが、手元でスペルチェックしたとき大丈夫かなと思ったやつです
- `.next/**`
- `.env.local`

2023-07-14 16:35 UTC, logica0419 commented on frontend/octavio/package.json
> +  "name": "ictsc_sachiko_3",
一応ここ変えておいて欲しいかも

2023-07-14 16:35 UTC, logica0419 commented on frontend/octavio/package.json
> +    "font": "docker build -f Dockerfile.font -t font-builder . && docker run -v $(pwd):/host -it font-builder sh -c \"cp /font/Variable/OTF/Subset/NotoSansJP-VF.woff2 /host/pages/NotoSansJP-VF.woff2
今回のPRと直接関係は無いですが、以下のように記述すると、マルチステージのDockerfileで指定したステージのみイメージとして出力できるので、これに置き換えて`Dockerfile.font`削除して欲しいです
```suggestion
    "font": "docker build --target font-builder -t font-builder . && docker run -v $(pwd):/host -it font-builder sh -c \"cp /font/Variable/OTF/Subset/NotoSansJP-VF.woff2 /host/pages/NotoSansJP-VF.woff2 && exit\""
```

2023-07-14 23:43 UTC, K-shir0 commented on frontend/octavio/package.json
> +    "font": "docker build -f Dockerfile.font -t font-builder . && docker run -v $(pwd):/host -it font-builder sh -c \"cp /font/Variable/OTF/Subset/NotoSansJP-VF.woff2 /host/pages/NotoSansJP-VF.woff2
こうすればよかったのか・・感謝です🙏

2023-07-15 00:01 UTC, K-shir0 commented
@logica0419 
指摘内容を修正しました。`.netx/**` や `.env.local` を確認したのですがどうやらドットファイルは無視されているっぽい挙動をしているのでそのままにしています。

2023-07-15 01:26 UTC, logica0419 approved these changes
LGTM、ありがとうございます！
ドットファイル含まれないなら良さそう

まあ不備があれば追々直していく、で良いかなと思います

2023-07-15 04:29 UTC, merged